image: node:12.18.4-alpine

before_script:
  - npm install
  - npm install -g serverless

stages:
  - qa
  - prd

cache:
  paths:
    - node_modules/

deploy_qa_job:
  stage: qa
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_DEV
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY_DEV
    - export TELEGRAM_KEY=$TELEGRAM_KEY_QA
    - sls deploy --stage qa --verbose
    - sls invoke --function webhookRegister
  environment:
    name: qa
  only:
    - qa


deploy_prd_job:
  stage: prd
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_DEV
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY_DEV
    - export TELEGRAM_KEY=$TELEGRAM_KEY_PRD
    - sls deploy --stage prd --verbose
    - sls invoke --function webhookRegister
  environment:
    name: prd
  only:
    - master


