service: tinkuy-bot

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: us-east-1
  environment:
    BASE_URL: https://api.telegram.org/bot${env:TELEGRAM_KEY}/sendMessage
    SET_WEBHOOK: https://api.telegram.org/bot${env:TELEGRAM_KEY}/setWebhook 
    LOCATION_URL: https://api.telegram.org/bot${env:TELEGRAM_KEY}/sendLocation
    PHOTOS_URL: https://api.telegram.org/bot${env:TELEGRAM_KEY}/sendPhoto
    
    SERVERLESS_REGION: us-east-1
    TABLE_TINKUY_COORDS: usr-coords-${self:custom.currentStage}
    TABLE_TINKUY_COORDS_HIST: usr-coords-hist-${self:custom.currentStage}
    TABLE_TINKUY_CLUSTER: tinkuy-clusters.${self:custom.currentStage}
    TABLE_POLICE_COORDS: police-coords-${self:custom.currentStage}

    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:PutItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Query"
        - "dynamodb:DeleteItem"
      Resource: "*"

custom:
  currentStage: ${opt:stage, self:provider.stage}
  stages:
    qa:
      stageName: qas
    prd:
      stageName: prd

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  webhookHandler:
    handler: app/handler.webhookHandler
    events:
      - http:
          path: webhook
          method: post
  webhookRegister:
    environment:
      API_INVOKE_ID: !Ref ApiGatewayRestApi
    handler: app/handler.webhookRegister
