service: tinkuy-bot

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  region: ${self:custom.stages.${self:custom.currentStage}.region}
  environment:
    BASE_URL: https://api.telegram.org/bot${env:TELEGRAM_KEY}/sendMessage
    SET_WEBHOOK: https://api.telegram.org/bot${env:TELEGRAM_KEY}/setWebhook 
    LOCATION_URL: https://api.telegram.org/bot${env:TELEGRAM_KEY}/sendLocation
    PHOTOS_URL: https://api.telegram.org/bot${env:TELEGRAM_KEY}/sendPhoto
    
    SERVERLESS_REGION: ${self:custom.stages.${self:custom.currentStage}.region}
    TABLE_TINKUY_COORDS: ${self:custom.db.coords.${self:custom.currentStage}}
    TABLE_TINKUY_COORDS_HIST: ${self:custom.db.coords-hist.${self:custom.currentStage}}
    TABLE_TINKUY_CLUSTER: ${self:custom.db.cluster.${self:custom.currentStage}}
    TABLE_POLICE_COORDS: ${self:custom.db.police.${self:custom.currentStage}}

    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:PutItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:Query"
        - "dynamodb:DeleteItem"
      Resource: "*"

custom:
  currentStage: ${opt:stage, self:provider.stage}
  stages:
    qa:
      stageName: qas
      region: us-east-1
    prd:
      stageName: prd
      region: us-east-1
  db:
    coords:
      qa: usr-coords-hist-qas
      prd: usr-coords-hist
    coords-hist:
      qa: tinkuy-coords-qas
      prd: tinkuy-coords
    cluster:
      qa: tinkuy-clusters-qas
      prd: tinkuy-clusters
    police:
      qa: poli-coords-qas
      prd: poli-coords

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  webhookHandler:
    handler: app/handler.webhookHandler
    events:
      - http:
          path: webhook
          method: post
  webhookRegister:
    environment:
      API_INVOKE_URL: !Ref ApiGatewayRestApi
    handler: app/handler.webhookRegister
