version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/node_modules
          verride-ci-command: npm install
workflows:
  build_bot:
    jobs:
      - build
  
