version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build, deploy and register
          command: |
            export TELEGRAM_KEY=$TELEGRAM_KEY_DEV
            export PATH="node_modules/.bin:$PATH"
            sls deploy --stage dev --verbose
            sls invoke --function webhookRegister --stage dev

workflows:
  main:
    jobs:
      - build_and_deploy
