version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm i -g serverless
      - node/install-packages:
          cache-path: node_modules/
          override-ci-command: npm install
      - save_cache:
          paths:
            - node_modules/
          key: bot-{{ checksum "package-lock.json" }}
    
workflows:
  build_bot:
    jobs:
      - build
      
  
