version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
  node: circleci/node@4.1.0

jobs: 
  build_and_deploy:
    parameters:
      telegram_key:
        default: $TELEGRAM_KEY_DEV
        type: env_var_name
    executor: node/default
    environment:
      AWS_DEFAULT_REGION: us-east-1
      TELEGRAM_KEY: <<parameters.telegram_key>>
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages:
          cache-version: v2
      - run:
          name: Deploy bot
          command: |
            export PATH="node_modules/.bin:$PATH"
            sls deploy --stage dev --verbose

  register_bot:
    parameters:
      telegram_key:
        default: $TELEGRAM_KEY_DEV
        type: env_var_name
    executor: node/default
    environment:
      AWS_DEFAULT_REGION: us-east-1
      TELEGRAM_KEY: <<parameters.telegram_key>>
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages:
          cache-version: v2
      - run:
          name: Register bot
          command: |
            export PATH="node_modules/.bin:$PATH"
            sls invoke --function webhookRegister --stage dev

workflows:
  main:
    jobs:
      - build_and_deploy
      - register_bot:
          requires:
            - build_and_deploy
