version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build:
    executor: node/default
    parameters:
      setup:
        default:
          - run: sudo npm install -g serverless
        type: steps
    steps:
      - checkout
      - steps: << parameters.setup >>
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          name: Set AWS credentials
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_DEV
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY_DEV
            export TELEGRAM_KEY=$TELEGRAM_KEY_DEV
            sls deploy --stage qa --verbose
    
workflows:
  build_bot:
    jobs:
      - build
      
  
