version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
  node: circleci/node@4.1.0
  serverless: circleci/serverless-framework@1.0.1

jobs: 
  build_and_deploy:
    executor: node/default
    parameters:
      deploy_env: 
        default: dev
        type: string
    environment:
      AWS_DEFAULT_REGION: us-east-1
      SERVERLESS_REGION: us-east-1
    steps:
      - checkout
      - aws-cli/setup
      - node/install-packages
      - serverless/setup
      - run:
          name: Deploy bot
          command: |
            source ./setup-env.sh
            serverless deploy --stage <<parameters.deploy_env>> --verbose

  register_bot:
    executor: aws-cli/default
    parameters:
      register_env: 
        default: dev
        type: string
    environment:
      AWS_DEFAULT_REGION: us-east-1
      FUNCTION_REGISTER_NAME: tinkuy-bot-<<parameters.register_env>>-webhookRegister
    steps:
      - aws-cli/setup
      - run:
          name: Register bot
          command: 
            aws lambda invoke --function-name $FUNCTION_REGISTER_NAME response.json

workflows:
  development:
    unless:
      and:
      - equal: [main, <<pipeline.git.branch>>]
    jobs:
      - build_and_deploy
      - register_bot:
          requires:
            - build_and_deploy
  production:
    when:
      and:
        - equal: [main, <<pipeline.git.branch>>]
    jobs:
      - build_and_deploy:
          deploy_env: prd
      - register_bot:
          register_env: prd
