version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Post Setup
          command: |
            echo "export PATH=node_modules/.bin:$PATH" >> $BASH_ENV
      - run:
          name: Deploy bot
          command: |
            export TELEGRAM_KEY=$TELEGRAM_KEY_DEV
            sls deploy --stage dev --verbose
      - run:
          name: Register bot
          command: |
            sls invoke --function webhookRegister --stage dev

workflows:
  main:
    jobs:
      - build_and_deploy
