version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build:
    executor: node/default
    parameters:
      setup:
        default:
          - run: sudo npm install -g serverless
        type: steps
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      TELEGRAM_KEY: $TELEGRAM_KEY
    steps:
      - checkout
      - steps: << parameters.setup >>
      - node/install-packages:
          cache-path: node_modules/
          override-ci-command: npm install
      - run: sls deploy --stage qa --verbose
      - run: invoke --function webhookRegister
      - save_cache:
          paths:
            - node_modules/
          key: bot-{{ checksum "package-lock.json" }}
    
workflows:
  build_bot:
    jobs:
      - build
      
  
