version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build and deploy
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_DEV
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY_DEV
            export TELEGRAM_KEY=$TELEGRAM_KEY_DEV
            export PATH="node_modules/.bin:$PATH"
            sls deploy --stage qa --verbose

workflows:
  main:
    jobs:
      - build_and_deploy
