version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build:
    executor: node/default
    parameters:
      setup:
        - run: "npm install -g serverless"
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/node_modules
          override-ci-command: npm install
    
workflows:
  build_bot:
    jobs:
      - build
  
