version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs: 
  build_and_deploy:
    executor: node/default
    parameters:
      setup:
        default:
          - run: sudo npm install -g serverless
        type: steps
    steps:
      - checkout
      - steps: << parameters.setup >>
      - node/install-packages
      - run:
          name: Set AWS credentials
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_DEV
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY_DEV
      - run:
          name: Set Telegram key
          command: export TELEGRAM_KEY=$TELEGRAM_KEY_DEV
      - run:
          name: Build and Deploy
          command: sls deploy --stage qa --verbose
    
workflows:
  main:
    jobs:
      - build_and_deploy
      
  
